### ISSUE TITLE
while usertags is enabled, clicking on your own user profile on bottom left next to the mute and deafen button doesn't work

### ISSUE THREAD

**Issue by jack652** [SrS2225a/BetterDiscord#13]
while usertags is enabled, clicking on your own user profile on bottom left next to the mute and deafen button doesn't work

**Comment by SrS2225a** [comment]
Hi, indeed does not sound right. Though you left out some minor details that I am a little confused about.

For example: In what way does it not work? Does your context user profile just not open? Or does the tags not get added for that particular user popout? 

And just to confirm you mean the user profile in the screenshot right?
![Screenshot_20220906_000106](https://user-images.githubusercontent.com/22408517/188568029-f1ba5c3f-c9e5-4e3c-a053-abf16996ed8e.png)

**Comment by SrS2225a** [comment]
You have not responded to this created issue in over a week. Therefore I am assuming that you resolved this issue and was fixed. If you still need help, feel free to create a new issue. Thanks!
