### ISSUE TITLE
FactOfTheDay Ambassador Theatre fact link missing parenthesis

### ISSUE THREAD

**Issue by aaronliu0130** [SrS2225a/BetterDiscord#19]
![image](https://user-images.githubusercontent.com/11874211/205759418-0d24bd2e-c1f4-46c6-80e2-fde7fecf0357.png)
The link leads to https://en.wikipedia.org/wiki/Ambassador_Theatre_(New_York_City instead of https://en.wikipedia.org/wiki/Ambassador_Theatre_(New_York_City)

I get this is an issue with the API but I don't see the repo for that and It's also by you

**Comment by aaronliu0130** [comment]
![image](https://user-images.githubusercontent.com/11874211/207203352-122ef265-f49a-4440-b2d4-88b8198d5120.png)
appears to happen for every fact with parens

**Comment by SrS2225a** [comment]
Hi there,
This is a known issue because of the way discord handles links. This is because discord thinks you are trying to wrap something in parentheses while trying to treat it as a link at the same time. Only discord can fix that bug
Sorry

**Comment by aaronliu0130** [comment]
Can't we use URL encoding?

**Comment by aaronliu0130** [comment]
Can't we use URL encoding? Like `New_York_City%29`
