### ISSUE TITLE
[FactOfTheDay] the fact in the plugin tumbnail is wrong ._.

### ISSUE THREAD

**Issue by tikkou** [SrS2225a/BetterDiscord#2]
![image](https://user-images.githubusercontent.com/71342961/172570880-46a7f690-6ac2-4c66-92f1-33a242c2cc88.png)
![image](https://user-images.githubusercontent.com/71342961/172570925-d47280cf-36d4-4df8-b564-ce545cc511b7.png)
![image](https://user-images.githubusercontent.com/71342961/172571334-0ff31b26-32ea-4bd7-ac6e-f8987215fdbf.png)

**Comment by SrS2225a** [comment]
Thanks for letting me know. The thumbnail is more meant as a "glace" at what exactly the plugin does.  Also the plugin pulls it's information from an api, so some information may be out of date or wrong. But if I remember correctly, spain in fact did lead the world in cork production once upon a time

**Comment by tikkou** [comment]
oldest info I could get was from 2010 and portugal still lead, anyway, just saying this bc it's not the best thing to have a wrong fact as the tumbnail
