### ISSUE TITLE
The button is missing

### ISSUE THREAD

**Issue by lordbagel42** [SrS2225a/BetterDiscord#20]
title says it all

**Comment by SrS2225a** [comment]
Are you referring to issue #18? You will see there why that plugin does not work, and why it has not been for a while. Sorry about the inconvenience of all this

**Comment by lordbagel42** [comment]
I would be, I couldn't find it because apparently I'm blind

**Comment by SrS2225a** [comment]
I see, in this case I will close this issue as it is a duplicate of the other one. But dont worry, I am trying to fix it asap. The Quick Switcher turned out to be a little harder to patch then I first thought
