### ISSUE TITLE
New lines creating new fact even if it's a part of the same fact

### ISSUE THREAD

**Issue by banna12345bob** [SrS2225a/BetterDiscord#3]
As stated above new lines on the fact website create a new fact even if it is a part of the same fact. this can be very confusing.
![image](https://user-images.githubusercontent.com/59811283/173223750-c6b38c69-51a3-436b-9c22-23e132c22bdc.png)
Fact shown on Discord
![image](https://user-images.githubusercontent.com/59811283/173223728-1e8cf8fb-33e9-47c1-b0cf-9cca944cc4fc.png)
Actual fact from source website

**Comment by Zzeyy** [comment]
Yes. Couldn't figure what was causing it. Now I know.

**Comment by SrS2225a** [comment]
I know, thank you. Plan on creating a parser for those cases, including markdowns. Just been busy with other things, so I have not been able to get started on that yet. I plan on doing that soon
